//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubeListSyncronizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YoutubeListSyncronizer.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading to {0}, are you sure?.
        /// </summary>
        internal static string ConfirmAreYouSure {
            get {
                return ResourceManager.GetString("ConfirmAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is not a valid youtube URL!.
        /// </summary>
        internal static string ExInvalidUrl {
            get {
                return ResourceManager.GetString("ExInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find resolution: .
        /// </summary>
        internal static string ExMessage {
            get {
                return ResourceManager.GetString("ExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube has banned your IP. Try again later..
        /// </summary>
        internal static string ExMessageBannedIP {
            get {
                return ResourceManager.GetString("ExMessageBannedIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video cannot be reached at the moment: Error:.
        /// </summary>
        internal static string ExVideoCannotBeReached {
            get {
                return ResourceManager.GetString("ExVideoCannotBeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is neither a Youtube Playlist nor a Youtube Video Link! Try links in other formats or report if you think this is a bug..
        /// </summary>
        internal static string NotValidUrl {
            get {
                return ResourceManager.GetString("NotValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Wrong Format.
        /// </summary>
        internal static string NotValidUrlTitle {
            get {
                return ResourceManager.GetString("NotValidUrlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists..
        /// </summary>
        internal static string StatusAlreadyExists {
            get {
                return ResourceManager.GetString("StatusAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed!.
        /// </summary>
        internal static string StatusCompleted {
            get {
                return ResourceManager.GetString("StatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} : {2}% - Syncronizing....
        /// </summary>
        internal static string StatusSyncronizing {
            get {
                return ResourceManager.GetString("StatusSyncronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncronization Complete!.
        /// </summary>
        internal static string SyncComplete {
            get {
                return ResourceManager.GetString("SyncComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total videos in this list:.
        /// </summary>
        internal static string TotalVideosInThisList {
            get {
                return ResourceManager.GetString("TotalVideosInThisList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; could not be accessed. Try to run this application as administrator, or select another path..
        /// </summary>
        internal static string WarningAccessDenied {
            get {
                return ResourceManager.GetString("WarningAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid url..
        /// </summary>
        internal static string WarningInvalidUrl {
            get {
                return ResourceManager.GetString("WarningInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No directory selected. Please select a directory to download into..
        /// </summary>
        internal static string WarningNoDirectorySelected {
            get {
                return ResourceManager.GetString("WarningNoDirectorySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Video Selected!.
        /// </summary>
        internal static string WarningNoVideoSelected {
            get {
                return ResourceManager.GetString("WarningNoVideoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No videos selected to download. Select at least one video to download!.
        /// </summary>
        internal static string WarningNoVideosSelectedToDownload {
            get {
                return ResourceManager.GetString("WarningNoVideosSelectedToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url is a youtube video link, instead of a playlist. Single video will be downloaded..
        /// </summary>
        internal static string WarningThisUrlIsAVideoLinkInsteadOfAPlaylist {
            get {
                return ResourceManager.GetString("WarningThisUrlIsAVideoLinkInsteadOfAPlaylist", resourceCulture);
            }
        }
    }
}
